version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: digital_library_app
    ports:
      - "80:5000"
    environment:
      - FLASK_ENV=development
    restart: always