"""add Library model, M2M Book-Library, add library_id to BorrowSlip

Revision ID: dd472b4fb681
Revises: 
Create Date: 2025-09-07 23:01:49.660641

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dd472b4fb681'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted with safety checks ###
    bind = op.get_bind()
    insp = sa.inspect(bind)

    if not insp.has_table('library'):
        op.create_table('library',
        sa.Column('library_id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=150), nullable=False),
        sa.Column('address', sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint('library_id'),
        sa.UniqueConstraint('name')
        )

    if not insp.has_table('library_book'):
        op.create_table('library_book',
        sa.Column('library_id', sa.Integer(), nullable=False),
        sa.Column('book_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['book_id'], ['book.book_id'], ),
        sa.ForeignKeyConstraint(['library_id'], ['library.library_id'], ),
        sa.PrimaryKeyConstraint('library_id', 'book_id')
        )
    with op.batch_alter_table('borrow_request', schema=None) as batch_op:
        # MySQL yêu cầu drop FK trước khi drop index phụ thuộc
        batch_op.drop_constraint(batch_op.f('borrow_request_ibfk_2'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('borrow_request_ibfk_2_idx'))
        batch_op.drop_column('book_id')

    with op.batch_alter_table('borrow_slip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('library_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'library', ['library_id'], ['library_id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('borrow_slip', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('library_id')

    with op.batch_alter_table('borrow_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('book_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('borrow_request_ibfk_2'), 'book', ['book_id'], ['book_id'])
        batch_op.create_index(batch_op.f('borrow_request_ibfk_2_idx'), ['book_id'], unique=False)

    op.drop_table('library_book')
    op.drop_table('library')
    # ### end Alembic commands ###
